name: test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres-version: ['16', '15', '14', '13', '12']

    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run tests pg_${{ matrix.postgres-version }}
      run: nix-shell --run "pg_${{ matrix.postgres-version }}_supa_audit make installcheck"
